## Multiple linear regression

In [2]:
# https://archive.ics.uci.edu/ml/datasets/Housing

from sklearn.datasets import load_boston
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# Get the Data
boston = load_boston()
boston["data"]

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [3]:
x_data = boston.data
y_data = boston.target.reshape(boston.target.size,1)

In [4]:
y_data.shape

(506, 1)

In [5]:
from sklearn import preprocessing

In [6]:
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0,5)).fit(x_data)
# standard_scale = preprocessing.StandardScaler().fit(x_data)
x_scaled_data = minmax_scale.transform(x_data)
x_scaled_data[:3]

array([[0.00000000e+00, 9.00000000e-01, 3.39076246e-01, 0.00000000e+00,
        1.57407407e+00, 2.88752635e+00, 3.20803296e+00, 1.34601570e+00,
        0.00000000e+00, 1.04007634e+00, 1.43617021e+00, 5.00000000e+00,
        4.48399558e-01],
       [1.17961270e-03, 0.00000000e+00, 1.21151026e+00, 0.00000000e+00,
        8.64197531e-01, 2.73998850e+00, 3.91349125e+00, 1.74480990e+00,
        2.17391304e-01, 5.24809160e-01, 2.76595745e+00, 5.00000000e+00,
        1.02235099e+00],
       [1.17848872e-03, 0.00000000e+00, 1.21151026e+00, 0.00000000e+00,
        8.64197531e-01, 3.47192949e+00, 2.99691040e+00, 1.74480990e+00,
        2.17391304e-01, 5.24809160e-01, 2.76595745e+00, 4.94868627e+00,
        3.17328918e-01]])

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(x_scaled_data, y_data, test_size=0.33)

In [9]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((339, 13), (167, 13), (339, 1), (167, 1))

In [10]:
from sklearn import linear_model

In [11]:
regr = linear_model.LinearRegression(fit_intercept=True,
                                    normalize=False,
                                    copy_X=True,
                                    n_jobs=8)
regr.fit(X_train, y_train)
regr

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=8, normalize=False)

In [12]:
regr.coef_ , regr.intercept_

(array([[-2.09302339,  0.80504048,  0.57258243,  0.46720372, -1.71508014,
          3.82047314,  0.09974429, -2.65595861,  1.20263313, -1.17916789,
         -1.9833808 ,  0.70555324, -3.85824622]]), array([25.88479695]))

In [13]:
# The coefficients
print('Coefficients: ', regr.coef_)
print('intercept: ', regr.intercept_)

Coefficients:  [[-2.09302339  0.80504048  0.57258243  0.46720372 -1.71508014  3.82047314
   0.09974429 -2.65595861  1.20263313 -1.17916789 -1.9833808   0.70555324
  -3.85824622]]
intercept:  [25.88479695]


In [14]:
regr.predict(x_data[:5])

array([[-55.83445605],
       [-25.20773875],
       [ -7.22026733],
       [ 13.31541392],
       [  7.02614177]])

In [15]:
x_data[:5].dot(regr.coef_.T) + regr.intercept_

array([[-55.83445605],
       [-25.20773875],
       [ -7.22026733],
       [ 13.31541392],
       [  7.02614177]])

In [16]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

In [17]:
y_true = y_test
y_hat = regr.predict(X_test)

In [18]:
r2_score(y_true, y_hat), mean_absolute_error(y_true, y_hat), mean_squared_error(y_true, y_hat)

(0.7094854760605607, 3.581533239565655, 29.238858168472852)

In [19]:
y_true = y_train
y_hat = regr.predict(X_train)

In [20]:
r2_score(y_true, y_hat), mean_absolute_error(y_true, y_hat), mean_squared_error(y_true, y_hat)

(0.7531373926911019, 3.0582699278264247, 18.845818598661044)

In [21]:
regr.score(X_test, y_test)

0.7094854760605607