# Pandas를 이용한 Spam 분석






In [1]:
from pandas import Series, DataFrame 
import pandas as pd 
import numpy as np

In [2]:
viagra_spam = { 'viagra': [1,0,0,0,0,0,0,0,1,1,1,0,0,1,0,0,0,0,0,1], 'spam': [ 1,0,0,0,0,0,1,0,1,0, 0,0,0,0,0,0,0,1,1,1 ]} 
df = pd.DataFrame(viagra_spam, columns = ['viagra', 'spam']) 
df.head()

viagra  spam
0       1     1
1       0     0
2       0     0
3       0     0
4       0     0

In [3]:
np_data = df.as_matrix() 
np_data[:3]

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[1, 1],
       [0, 0],
       [0, 0]], dtype=int64)

In [4]:
p_viagra = sum(np_data[:, 0] == 1) / len(np_data) 
p_spam = sum(np_data[:, 1] == 1) / len(np_data) 
p_v_cap_s = sum((np_data[:, 0] == 1) & (np_data[:, 1] == 1)) / len(np_data) 
p_n_v_cap_s = sum((np_data[:, 0] == 0) & (np_data[:, 1] == 1)) / len(np_data)

In [5]:
p_spam * (p_v_cap_s / p_spam ) / p_viagra

0.5

In [6]:
p_spam * (p_n_v_cap_s / p_spam ) / (1-p_viagra)

0.2142857142857143

In [7]:
data_url = "./fraud.csv" 
df= pd.read_csv(data_url, sep=',') 
df.head(10)

ID  History CoApplicant Accommodation  Fraud
0   1  current        none           own   True
1   2     paid        none           own  False
2   3     paid        none           own  False
3   4     paid   guarantor          rent   True
4   5  arrears        none           own  False
5   6  arrears        none           own   True
6   7  current        none           own  False
7   8  arrears        none           own  False
8   9  current        none          rent  False
9  10     none        none           own   True

In [8]:
del df["ID"] 
Y_data = df.pop("Fraud") 
Y_data = Y_data.as_matrix() 
Y_data 

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  This is separate from the ipykernel package so we can avoid doing imports until


array([ True, False, False,  True, False,  True, False, False, False,
        True, False,  True,  True, False, False, False, False, False,
       False, False])

In [9]:
df.head() 

History CoApplicant Accommodation
0  current        none           own
1     paid        none           own
2     paid        none           own
3     paid   guarantor          rent
4  arrears        none           own

In [10]:
x_df = pd.get_dummies(df) 
x_df.head() 

History_arrears  History_current  History_none  History_paid  \
0                0                1             0             0   
1                0                0             0             1   
2                0                0             0             1   
3                0                0             0             1   
4                1                0             0             0   

   CoApplicant_coapplicant  CoApplicant_guarantor  CoApplicant_none  \
0                        0                      0                 1   
1                        0                      0                 1   
2                        0                      0                 1   
3                        0                      1                 0   
4                        0                      0                 1   

   Accommodation_free  Accommodation_own  Accommodation_rent  
0                   0                  1                   0  
1                   0                  1                   0  
2                   0                  1                   0  
3                   0                  0                   1  
4                   0                  1                   0

In [11]:
x_data = x_df.as_matrix() 
x_data[:3] 

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[0, 1, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 1, 0, 1, 0]], dtype=uint8)