## Titanic random forest(classification)

In [2]:
import numpy as np

In [3]:
X = np.load("./tatanic_X_train.npy")
y = np.load("./tatanic_y_train.npy")

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, \
                            test_size=0.3, random_state=101)

In [5]:
X_train[0]

array([0.22334962, 0.01517579, 0.        , 1.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.        , 1.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])

In [6]:
y_train[:10]

array([0., 1., 1., 1., 0., 0., 1., 1., 0., 1.])

In [7]:
from sklearn.ensemble import RandomForestClassifier
eclf = RandomForestClassifier(n_estimators=100, max_features=2, \
                              n_jobs=7, oob_score=True)

In [8]:
from sklearn.model_selection import cross_val_score
cross_val_score(eclf, X_train, y_train, cv=5).mean()

0.7975166410650282

In [10]:
params ={
    "n_estimators" : [10, 20, 30, 50, 100],
    "max_features" : [1,2,3,4,5,6,7, 10, 15, 20, 25, len(X[0])]
    }

In [13]:
params

{'n_estimators': [10, 20, 30, 50, 100],
 'max_features': [1, 2, 3, 4, 5, 6, 7, 10, 15, 20, 25, 27]}

In [14]:
eclf

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features=2, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=7,
            oob_score=True, random_state=None, verbose=0, warm_start=False)

In [12]:
# cross_val_score - cross validation
# GridSearchCV - cross validation, parm grid search, model return

# gridsearchcv operation

from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(estimator = eclf, param_grid=params, cv=5)
grid = grid.fit(X_train, y_train)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:463: RuntimeWarning: invalid value encountered in true_divide
  predictions[k].sum(axis=1)[:, np.newaxis])
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:463: RuntimeWarning: invalid value encountered in true_divide
  predictions[k].sum(axis=1)[:, np.newaxis])
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: UserWarning: Some inputs do not have OOB scores. This probably means t

## Searching for best params

In [10]:
grid.best_score_

0.8295819935691319

In [11]:
grid.best_params_

{'max_features': 25, 'n_estimators': 100}

In [12]:
grid.best_estimator_.oob_score_

0.797427652733119

In [13]:
grid.best_estimator_

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features=25, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=7,
            oob_score=True, random_state=None, verbose=0, warm_start=False)

In [15]:
predictions = grid.predict(X_test)
from sklearn.metrics import confusion_matrix, classification_report


In [16]:
grid.score(X_test, y_test)

0.8389513108614233

In [17]:
# confusion matrix
confusion_matrix(y_test, predictions)

array([[147,  16],
       [ 27,  77]], dtype=int64)

In [18]:
# classification report
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.84      0.90      0.87       163
         1.0       0.83      0.74      0.78       104

   micro avg       0.84      0.84      0.84       267
   macro avg       0.84      0.82      0.83       267
weighted avg       0.84      0.84      0.84       267



In [19]:
btree = RandomForestClassifier(max_features = 20, n_estimators = 20)

In [20]:
btree.fit(X_train, y_train)
btree.score(X_test, y_test)

0.850187265917603

In [21]:
btree.feature_importances_

array([0.22374597, 0.21499196, 0.02327832, 0.07106653, 0.20273959,
       0.04179504, 0.01466188, 0.01172438, 0.005439  , 0.01387563,
       0.00151413, 0.0012893 , 0.00110805, 0.00828048, 0.00624438,
       0.11419543, 0.0035994 , 0.00514539, 0.01102572, 0.00085573,
       0.00430652, 0.00752242, 0.00538014, 0.00570435, 0.        ,
       0.00051027, 0.        ])